import "@img/devchallenges.png";
import "@img/profilePhoto.png";
import "@img/photo1.png";
import "@img/photo2.png";
import "@img/photo3.png";
import "@img/photo4.png";
import "@img/photo5.png";
import "@img/photo6.png";
import "@scss/main.scss";
